from db_connection import get_engine
import pandas as pd
from faker import Faker
import random

random.seed(42)
Faker.seed(42)
fake = Faker()

engine = get_engine()

# Read IDs generated by PostgreSQL
locations_df = pd.read_sql(
    "SELECT location_id, name FROM locations",
    engine
)

departments_df = pd.read_sql(
    "SELECT department_id, name FROM departments",
    engine
)

roles_by_department = {
    "Sales Floor": [
        "Sales Associate",
        "Senior Sales Associate"
    ],
    "Stockroom": [
        "Stock Clerk",
        "Inventory Associate"
    ],
    "Customer Service": [
        "Customer Service Rep",
        "Service Lead"
    ],
    "Cash Counter": [
        "Cashier",
        "Head Cashier"
    ],
    "Management": [
        "Assistant Manager",
        "Store Manager"
    ]
}

base_hourly_rate = {
    "Sales Associate": 14,
    "Senior Sales Associate": 17,
    "Stock Clerk": 13,
    "Inventory Associate": 14,
    "Customer Service Rep": 15,
    "Service Lead": 18,
    "Cashier": 13,
    "Head Cashier": 16,
    "Assistant Manager": 22,
    "Store Manager": 28
}

employees = []

for _ in range(100):

    location = locations_df.sample(1).iloc[0]
    department = departments_df.sample(1).iloc[0]

    role = random.choice(
        roles_by_department[department["name"]]
    )

    hourly_rate = round(
        base_hourly_rate[role] * random.uniform(0.9, 1.1),
        2
    )

    hire_date = fake.date_between(
        start_date="-5y",
        end_date="-30d"
    )

    employees.append({
        "full_name": fake.name(),
        "department_id": int(department["department_id"]),
        "location_id": int(location["location_id"]),
        "role": role,
        "hourly_rate": hourly_rate,
        "hire_date": hire_date
    })

employees_df = pd.DataFrame(employees)

employees_df.to_sql(
    "employees",
    con=engine,
    if_exists="append",
    index=False
)

print(f"Inserted {len(employees_df)} employees.")
print(employees_df["role"].value_counts())